---
all:
  children:
    fabric:
      children:
        spine:
          hosts:
            spine01:
              ansible_host: 172.20.20.11
              loopback_address: 10.255.0.1
              bgp_asn: 65001
            spine02:
              ansible_host: 172.20.20.12
              loopback_address: 10.255.0.2
              bgp_asn: 65001
        leaf:
          hosts:
            leaf01:
              ansible_host: 172.20.20.21
              loopback_address: 10.255.0.11
              bgp_asn: 65011
            leaf02:
              ansible_host: 172.20.20.22
              loopback_address: 10.255.0.12
              bgp_asn: 65012
            leaf03:
              ansible_host: 172.20.20.23
              loopback_address: 10.255.0.13
              bgp_asn: 65013
        border_leaf:
          hosts:
            border-leaf01:
              ansible_host: 172.20.20.24
              loopback_address: 10.255.0.14
              bgp_asn: 65014
